server:
  port: 8099
spring:
  application:
    name: bus-arrive
xiaoyuan:
  key: 632e6732f9e1a6bd4b3b4966a9009bcd
  username: 15610462126
  url: http://api.dwmm136.cn/z_busapi/BusApi.php
remembor:
  cityandroute:
    杭州市 353,杭州市 415
amap:
  key: ca749b4a5f0fe299e8cd826f69c1c6bc
  sign: 0dcee3a9115b5782fecfa7f90f876981
  amapGetStationUrl: https://restapi.amap.com/v3/geocode/geo
  busRouteTimeUrl: https://restapi.amap.com/v5/direction/transit/integrated


