server:
  port: 24504
spring:
  application:
    name: bus-arrive
logging:
  level:
    root: info
    com.bestvike: debug
    org.springframework.security: warn
  config: classpath:logback.xml
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 公交到达预提醒
  try-host: http://localhost:${server.port}
xiaoyuan:
  key: 632e6732f9e1a6bd4b3b4966a9009bcd
  username: 15610462126
remembor:
  cityandroute:
    杭州市 353,杭州市 415
amap:
  key: ca749b4a5f0fe299e8cd826f69c1c6bc
  sign: 0dcee3a9115b5782fecfa7f90f876981
bus-arrive:
  default-difference-seconds: 180

# 相关api的url地址配置在UrlTypeEnum中


