server:
  port: 8099
spring:
  application:
    name: bus-arrive
xiaoyuan:
  url:
  key: 632e6732f9e1a6bd4b3b4966a9009bcd
  username: 15610462126
remembor:
  cityandroute:
    杭州市 353,杭州市 415
amp:
  key: ca749b4a5f0fe299e8cd826f69c1c6bc
