server:
  port: 8081
spring:
  application:
    name: bus-arrive
  redis:
    database: 0
    host: 自己的redisip
    port: redis对外暴露端口
    password: redis密码
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 3000
logging:
  level:
    root: info
    com.bestvike: debug
    org.springframework.security: warn
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 公交到达预提醒
  try-host: http://localhost:${server.port}
xiaoyuan:
  key: 笑园api申请的key值
  username: 笑园api用户名
remembor:
  cityandroute:
    杭州市 353,杭州市 415
amap:
  key: 高德api申请的key值
  sign: 高德api申请的签名
bus-arrive:
  default-difference-seconds: 180

# 相关api的url地址配置在UrlTypeEnum中


