server:
  port: 24507
spring:
  application:
    name: bus-arrive
  redis:
    database: 0
    host: 43.132.237.240
    port: 24505
    password: 132Anly132
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 3000
logging:
  level:
    root: info
    com.bestvike: debug
    org.springframework.security: warn
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 公交到达预提醒
  try-host: http://localhost:${server.port}
xiaoyuan:
  key: 632e6732f9e1a6bd4b3b4966a9009bcd
  username: 15610462126
remembor:
  cityandroute:
    杭州市 353,杭州市 415
amap:
  key: ca749b4a5f0fe299e8cd826f69c1c6bc
  sign: 0dcee3a9115b5782fecfa7f90f876981
bus-arrive:
  default-difference-seconds: 180

# 相关api的url地址配置在UrlTypeEnum中


